@startuml
title Iran Dade Data Model


package "Visualization" as visualization_package{

    class Chart  <<ManagerMixin>> #paleturquoise{
        chart_uid : UUID
        name : str
        description : str
    }

    class Dashboard  <<ManagerMixin>> #paleturquoise{
        dashboard_uid : UUID
        name : str
        description : str
    }

    class Card <<ManagerMixin>> #paleturquoise{

    }

    Chart "*" -- "*" Dashboard
}




package Utils{
' Kind of measure used for observation
    entity MeasureKind  #skyblue {
      measure_kind_uid : UUID
      name : string
      alt_name : string
      unit : varchar(50)
      unit_coefficient : int
      description : text
    }



    enum   CurrencyType <<code>> #beige{
        IIR<IIR>

        USD<USD>


    }




    enum ValueType <<code>> #beige{
       DECIMAL<DEC>
       FLOAT<FLT>

    }


    MeasureKind "*"-up-"1" ValueType : <<code>>

    enum   CurrencyExchangeType #beige{
        CB_Market
        FREE_Market

    }
    class CurrencyExchangeRate <<ManagerMixin>>  #pink{
        currency_exchange_rate_uid : UUID
        rate_at : datetime
        value : int

    }

    CurrencyExchangeRate -- CurrencyExchangeType : base
    CurrencyExchangeRate -- CurrencyType : base
    CurrencyExchangeRate -- CurrencyType : quote

}



package "Meta Data" as metadata_package{

    class GeographyDimension #lightgreen{
        geography_dimension_uid : UUID
        name_fa : str
        name_en : str
        description_fa : text
        description_en : text
        valid_start_at : datetime
        valid_end_at : datetime
    }

    enum GeographyStateType <<code>> #beige{
        PROVINCE<PRO>
        TERRITORY<TRI>
        STATE<STA>


    }
    enum GeographyDimType <<code>> #beige{

        CONTINENT<CON>
        COUNTRY<COU>
        STATE<STA>
        COUNTY<CTY>
        CITY<CIT>
    }

    GeographyDimension "*"--"1" GeographyDimType : <<code>>
    GeographyDimension "*"--"0-1" GeographyStateType : <<code>>

    GeographyDimension "n"--"0-1" GeographyDimension : parent/child

    class TimeDimension  <<ManagerMixin>> #lightgreen{
        time_dimension_uid : UUID
        name : str
        description : str
        after_origin : bool
        century_value : int
        year_value : int
        month_value : int
        day_value : int
        day_of_week_value : int
        date_value : date
        datetime_value : datetime
    }

    TimeDimension "n"--"0-1" TimeDimension : parent/child

    class DayDimension #lightgreen{
        day_dimension_uid : UUID
        grg_name : str
        jal_name : str
        lun_name : str
        grg_century : int
        grg_year : int
        grg_month : int
        grg_day : int
        grg_day_of_week : int
        jal_century : int
        jal_year : int
        jal_month : int
        jal_day : int
        jal_day_of_week : int
        date_value : date
    }

DayDimension "n" -- "0-1" TimeDimension : grg_month
DayDimension "n" -- "0-1" TimeDimension : jal_month

    enum CalendarType <<code>> #beige{

        LUNAR<LUN>
        GREGORIAN<GRG>
        JALALI<JAL>

    }

    TimeDimension -- CalendarType : <<code>>
    enum TimeDimensionType <<code>> #beige{


        CENTURY<CEN>
        YEAR<YEA>
        MONTH<MON>
        QUARTER<QRT>
        WEEK<WEE>
        DAY<DAY>

    }





    TimeDimension -- TimeDimensionType : <<code>>


    enum ConceptLevelType <<code>> #beige{
        CLUSTER<CLS>
        DOMAIN<DOM>
        SUBDOMAIN<SDO>
        TOPIC<TOP>


    }

    ' Concept
    ' A conceptual topic or subject area used to organize knowledge.
    ' Concepts represent what is being studied or analyzed
    ' levels are in ConceptLevelType
    ' (e.g., Inflation, Unemployment, GDP, Poverty).
    class Concept  <<ManagerMixin>> #lightgreen{
        concept_uid : uuid
        created_at : datetime
        name : str
        alt_name1 : str
        alt_name2 : str
        alt_name3 : str
        description : str
    }

    Concept "*"--"1" ConceptLevelType : <<code>>

    Concept "n"--"0-1" Concept : parent/child

    ' Dimension Kind
    ' Defines a classification axis used to segment or analyze
    ' measures.
    ' Time  Dimensions exceptionally managed in DayDimension,TimeDimension
    ' Geography  Dimensions exceptionally managed in GeographyDimension
    ' Dimension kinds describe the type of breakdown, such as:
    ' - Gender
    ' - Age Group


    class DimensionKind  <<ManagerMixin>> #lightgreen{
        dimension_kind_uid : uuid
        created_at : datetime
        name : str
        alt_name1 : str
        alt_name2 : str
        alt_name3 : str

        description : str
    }


    ' Dimension Value
    ' A specific member of a dimension kind.
    '
    ' Dimension values provide the actual category used in a
    ' measure breakdown.
    '
    ' Examples:
    ' Dimension Kind: Geography
    ' Values: Iran, Tehran Province, Isfahan Province
    '
    ' Dimension Kind: Gender
    ' Values: Male, Female
    class DimensionValue  <<ManagerMixin>> #lightgreen{
        dimension_value_uid : uuid
        created_at : datetime
        name : str
        alt_name1 : str
        alt_name2 : str
        alt_name3 : str

        description : str
    }



   DimensionValue "n"--"1" DimensionKind
   DimensionValue "n"--"0-1" DimensionValue :parent/child





}


package "Data" as data_package{




' Observation
' A quantitative observation of an indicator for a specific
' time period and dimensional context.
'
' A Observation contains the actual reported value together with
' its unit, methodology, source, and dimensional breakdowns.
'
' Example:
' Inflation Rate = 35.2%
' Country = Iran
' Year = 2024
    class Observation #skyblue {
      observation_uid : UUID
      decimal_value : decimal
      float_value : decimal
    }



    enum ObservationsType <<code>> #beige{
        FORMAL<FRM>
        SEMIFORMAL<SFM>

        INFORMAL<INF>

    }

    Observation "*"-up-"1" ObservationsType : <<code>>

' Indicator
' A measurable statistical indicator associated with a concept.
' Indicators define what is observed or reported and may
' be represented by one or more measures over time.
' list of data will be stored in observation
'
' Examples:
' - Inflation Rate
' - Unemployment Rate
' - GDP Growth Rate
    class Indicator<<BE>> #skyblue{
        indicator_uid : uuid
        name : str
        description : str
    }

    class ObservationDimensionValueRel #lightcyan{
        observation_uid : UUID
        dimension_value_uid : UUID
    }

    ObservationDimensionValueRel "*" -- "1" Observation
    ObservationDimensionValueRel "*" -- "1" DimensionValue
    Observation "n"-down-"0-1" GeographyDimension
    Observation "n"-down-"0-1" TimeDimension

    MeasureKind "1"--"n" Observation

}






Observation "*" -up- "1" Indicator

Indicator "*"--"*" Concept

@enduml