@startuml
title Iran Dade Data Model


package "Visualization" as visualization_package{

    class Chart  <<ManagerMixin>> #paleturquoise{
        uuid chart_uid
        str name
        str description
    }

    class Dashboard  <<ManagerMixin>> #paleturquoise{
        uuid dashboard_uid
        str name
        str description
    }

    class Card <<ManagerMixin>> #paleturquoise{

    }

    Chart "*" -- "*" Dashboard
}




package "Source" as source_pkg{

    class Organization #linen{
        uuid organization_id
        string name
        string description
        bool is_domestic
        string website
    }



    class SourceDocument #linen{
        uuid source_id
        string url
        string os_path
        SourceType source_type_code
        datetime fetched_at

    }

    enum SourceType #linen{
        WEB<WEB>
        PDF<PDF>
        WORD<WRD>
        EXCEL<EXC>
        PRESENTATION<PRS>
    }


    SourceDocument "*"--"1" Organization
}
package Utils{


    enum   UnitType #beige{

        '   distance
        METER<MTR>
        ' something like inflation
        UNIT<UNT>
        '   area
        SQUARE_METER<MT2>
        PERSON<PRS>
        IIR<IIR>
        USD<USD>
        PERCENT<PCT>
        INDEX_PONT<IXP>


    }

    enum   CurrencyType  #beige{
        IIR<IIR>
        USD<USD>
    }




    enum   CurrencyExchangeType #beige{
        CB_MARKET<CBM>
        FREE_MARKET<FRM>

    }
    class CurrencyExchangeRate <<ManagerMixin>>  #pink{
        uuid currency_exchange_rate_uid
        datetime rate_at
        decimal value
        CurrencyExchangeType : exchange_type
        CurrencyType : base_currency_type
        CurrencyType : quote_currency_type
    }



}



package "Meta Data" as metadata_package{

    ' Kind of measure used for observation
    class measure_kind  #lightgreen {
      uuid measure_kind_uid
      string name
      string alt_name
      string unit
      UnitType unit_type_code
      CurrencyType currency_type_code
      int unit_coefficient
      int base_year
      text description
    }

    class GeographyDimension #lightgreen{
        uuid geography_dimension_uid
        str name_fa
        str name_en
        text description_fa
        text description_en
        string code
        datetime valid_start_at
        datetime valid_end_at

        GeographyDimType geography_dim_type_code
        SubCountryType state_type_code
    }

    enum SubCountryType  #beige{
        PROVINCE<PRO>
        TERRITORY<TRI>
        STATE<STA>


    }
    enum GeographyDimType  #beige{

        CONTINENT<CON>
        COUNTRY<COU>
        STATE<STA>
        COUNTY<CTY>
        CITY<CIT>
    }



    GeographyDimension "n"--"0-1" GeographyDimension : parent/child

'    some period of tome like month,year in some calendar like year 1404 in jalali cal
    class TimeDimension  <<ManagerMixin>> #lightgreen{
        uuid time_dimension_uid
        str name
        str description
        bool after_origin
        int century_value
        int year_value
        int month_value
        int day_value
        int day_of_week_value
        date date_value
        datetime datetime_value
        CalendarType calendar_type_code

        TimeDimensionType time_dimension_type_code

    }

    TimeDimension "n"--"0-1" TimeDimension : parent/child

' real calendar day in some calendar
    class DayDimension #lightgreen{
        uuid day_dimension_uid
        str grg_name
        str jal_name
        str lun_name
        int grg_century
        int grg_year
        int grg_month
        int grg_day
        int grg_day_of_week
        int jal_century
        int jal_year
        int jal_month
        int jal_day
        int jal_day_of_week
        date date_value
    }

DayDimension "n" -up- "0-1" TimeDimension : grg_month
DayDimension "n" -up- "0-1" TimeDimension : jal_month

    enum CalendarType  #beige{

        LUNAR<LUN>
        GREGORIAN<GRG>
        JALALI<JAL>

    }


    enum TimeDimensionType  #beige{


        CENTURY<CEN>
        YEAR<YEA>
        MONTH<MON>
        QUARTER<QRT>
        WEEK<WEE>
        DAY<DAY>

    }






    enum ConceptLevelType  #beige{
        CLUSTER<CLS>
        DOMAIN<DOM>
        SUBDOMAIN<SDO>
        TOPIC<TOP>


    }

    ' Concept
    ' A conceptual topic or subject area used to organize knowledge.
    ' Concepts represent what is being studied or analyzed
    ' levels are in ConceptLevelType
    ' (e.g., Inflation, Unemployment, GDP, Poverty).
    class Concept  <<ManagerMixin>> #lightgreen{
        uuid concept_uid
        datetime created_at
        str name
        str alt_name1
        str alt_name2
        str alt_name3
        str description
        ConceptLevelType level_type_code
    }



    Concept "n"--"0-1" Concept : parent/child

    ' Dimension Kind
    ' Defines a classification axis used to segment or analyze
    ' measures.
    ' Time  Dimensions exceptionally managed in DayDimension,TimeDimension
    ' Geography  Dimensions exceptionally managed in GeographyDimension
    ' Dimension kinds describe the type of breakdown, such as:
    ' - Gender
    ' - Age Group


    class dimension_kind  <<ManagerMixin>> #lightgreen{
        uuid dimension_kind_uid
        datetime created_at
        str name
        str alt_name1
        str alt_name2
        str alt_name3

        str description
    }


    ' Dimension Value
    ' A specific member of a dimension kind.
    '
    ' Dimension values provide the actual category used in a
    ' measure breakdown.
    '
    ' Examples:
    ' Dimension Kind: Geography
    ' Values: Iran, Tehran Province, Isfahan Province
    '
    ' Dimension Kind: Gender
    ' Values: Male, Female
    class DimensionValue  <<ManagerMixin>> #lightgreen{
        uuid dimension_value_uid
        datetime created_at
        str name
        str alt_name1
        str alt_name2
        str alt_name3

        str description
    }


' Indicator
' A measurable statistical indicator associated with a concept.
' Indicators define what is observed or reported and may
' be represented by one or more measures over time.
' list of data will be stored in observation
'
' Examples:
' - Inflation Rate
' - Unemployment Rate
' - GDP Growth Rate
    class Indicator<<BE>> #lightgreen{
        uuid indicator_uid
        str name
        str description
    }

   DimensionValue "n"--"1" dimension_kind
   DimensionValue "n"--"0-1" DimensionValue :parent/child


' Series
' A data series grouping observations for an indicator
' measured in a specific unit with a defined formality
' and time granularity.
    class Series<<BE>> #skyblue{
        uuid series_uid
        str name
        str description
        FormalityType formality_type_code
        TimeDimensionType time_dimension_type_code
    }


}


package "Data" as data_package{




' Observation
' A quantitative observation of a dataset for a specific
' time period and dimensional context.
'
' A Observation contains the actual reported value together with
' its unit, methodology, source, and dimensional breakdowns.
'
' Example:
' Inflation Rate = 35.2%
' Country = Iran
' Year = 2024
    class Observation #skyblue {
      uuid observation_uid
      decimal decimal_value
      decimal float_value
      ObservationType observation_type_code
      FormalityType formality_type_code [0..1]
      ReviewStatusType review_status_type_code
      datetime published_at
    }


    enum ReviewStatusType #beige{
        DISCOVERED<DSC>
        REVIEWED<REV>
    }


    enum ObservationType #beige{
        OBSERVED<OBS>
        ESTIMATED<EST>

    }

    enum FormalityType  #beige{
        FORMAL<FRM>
        SEMIFORMAL<SFM>
        INFORMAL<INF>
        MIXED<MIX>

    }










' from every dimentsionkind just one dimenstion value can be relate to single observation
    Observation "*" -- "*" DimensionValue


    Observation "n"-down-"0-1" GeographyDimension
    Observation "n"-down-"0-1" TimeDimension

    measure_kind "1"--"n" Series

    Observation "n"--"1" SourceDocument
}






    Series "1" -- "*" Observation



    Indicator "1"-up-"*" Series
    Indicator "*"-down-"1" Concept

@enduml
